### ISSUE TITLE
 'rviz_plugins/GameLikeInput' failed to load

### ISSUE THREAD

**Issue by snakehaihai** [SmartGroupSystems/Dynamic-Planner#1]
[librospack]: error while executing command
[ERROR] [1725876558.153206079]: PluginlibFactory: The plugin for class 'rviz_plugins/GameLikeInput' failed to load.  Error: MultiLibraryClassLoader: Could not create class of type GameLikeInput

Can help to provide the reference for this package?

**Comment by RicardoLEE123** [comment]
Hi,
The plugin is not used in this simulation, so this error can be ignored.
